package Interpreter;

public enum TokenType{		//These are the token types
	ADD, SUBTRACT, MULTIPLY, DIVIDE, NUMBER, NL, EOF,NULL,ASSIGNMENT,
	LESS, GREATER, EQUAL, NOTEQUAL, LESSEQUAL, GREATEREQUAL, OR, AND, LPARENT,
	RPARENT, PRINT, MAIN, END, KEYWORD,STRING,LET,TERMIN,
}
